"""This is a first version of mid player to be able to play the abc notes
generated by Markov chain. At the moment hard-coded for testing purposes."""

from music21 import converter
import pygame


s = converter.parse('src/music/generated.abc')
s.write('midi', fp='src/music/output.mid')

pygame.init() # pylint: disable=[no-member]
clock = pygame.time.Clock()
pygame.mixer.music.load("src/music/output.mid")
pygame.mixer.music.play()
while pygame.mixer.music.get_busy():
    pygame.event.poll()
    clock.tick(10)

print("Now pygame is playing")






